### PR TITLE
Translate to Norwegian

### PR DESCRIPTION
**Pull request by piprett**
I translated to Norwegian. I know it isent a lot of translation keys (only one), but I am trying to translate ModFest:Singularity to Norwegian.

### CODE REVIEW

**Comment by woodiertexas** [comment]
Norwegian isn't my native language so I put "Kantklipper" into Google Translate and it gave me "Edge trimmer". I'm not entirely sure if that's the correct translation for "weedwhacker" since Google Translate gave me "gresshaker" as the Norwegian word for "weedwhacker".

image

**Comment by piprett** [comment]
Yeah, uh, "gresshaker" isent really a Norwegian word I have ever heard of before. "Kantklipper", which is Edge Trimmer, was the closest i came. I guess i can make it "weed eater" (ugress eter) if that is better?

**Comment by woodiertexas** [comment]
"weed eater" (ugress eter) works.

**Comment by piprett** [comment]
> "weed eater" (ugress eter) works.

Fixed 👍

**Comment by woodiertexas** [comment]
Thanks for putting the translation together.

**Pull request merged**
